### ISSUE TITLE
Provide a way to sync the state with i.e. the parent component

### ISSUE THREAD

**Issue by ForsakenHarmony** [MobiusHorizons/mu-forms#5]
i.e. `onChange` on the form

**Comment by MobiusHorizons** [comment]
could you please explain your use-case? There are several ways this could be implemented, and I would like to ensure I am designing the feature correctly.

**Comment by ForsakenHarmony** [comment]
I need to conditionally change the options of a select based on another input

**Comment by MobiusHorizons** [comment]
Use connectForm. It passes in status.data, which has all the form values

**Comment by ForsakenHarmony** [comment]
But I need it outside the form

render prop would be an option ig

**Comment by MobiusHorizons** [comment]
Ah gotcha.

**Comment by ForsakenHarmony** [comment]
Like the field should not be aware of it

I have a 2 selects and want to filter the options of one based on the selected option of the other

If you think there's a decent way to do that already feel free to tell me, but I don't want to mix in a lot of code in the jsx of the component containing the form and adding a `connectForm` just seems ugly

**Comment by MobiusHorizons** [comment]
the way I handled this was to wrap the select that has the complex behavior like so:


```
const _DependentSelect = ({ status, categoryOptions = {}, ...props }) = {
    let options = possibleOptions[status.data.category];
    return (
        <Select options={options} {...props} />
    );
}
const DependentSelect = connectForm(_DependentSelect);

<Form>
    ....
    <Select name="category" .../>
    <DependentSelect name="subCat" categoryOptions={...} />
</Form>
```

However, I see your point that this is not ideal.
For this reason, I am adding an `onChange` like you requested. It will be available in `v1.06`

**Comment by MobiusHorizons** [comment]
the new `onChange` feature is documented here: https://github.com/mobiushorizons/mu-forms#onchange

**Comment by ForsakenHarmony** [comment]
Cool thx

**Comment by ForsakenHarmony** [comment]
Uhh it doesn't seem to work, `onChange` gives me input events

**Comment by MobiusHorizons** [comment]
Oh, it must be passing it through to the form. I'll address it right away.

**Comment by ForsakenHarmony** [comment]
No sorry, was a problem on my side

works fine now, had another problem with it being in a rerender loop because I'd set the parents state which would also update the child form -> another change, but I just check if it's new now

**Comment by MobiusHorizons** [comment]
Thanks for the update.
